### ISSUE TITLE
[BUG] Minimap icons not shown in game

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [oblivioncth/Stexatlaser#15]
![stex](https://github.com/oblivioncth/Stexatlaser/assets/55184223/088fa72b-92dd-4daa-bf78-80b6c332ad78)
![texture](https://github.com/oblivioncth/Stexatlaser/assets/55184223/26450e84-c21b-4e2c-a1ef-aed9d76b844a)
The minimap atlas of STex looks black in game, while that of Texture and Atlas Packer and of ztools looks correct.

**Comment by ZzzzzzzSkyward** [comment]
Here are the files.
[images.zip](https://github.com/oblivioncth/Stexatlaser/files/12326728/images.zip)

**Comment by oblivioncth** [comment]
Is `wokey_minimap.tex` the one created with Texture and Atlas Packer?

**Comment by ZzzzzzzSkyward** [comment]
> Is `wokey_minimap.tex` the one created with Texture and Atlas Packer?

Yes.

**Comment by oblivioncth** [comment]
I did make a small change so you can see if the latest build from CI in the `dev` branch happens to work but I don't think that was the issue yet.

**Comment by ZzzzzzzSkyward** [comment]
Great! This issue is fixed.

**Comment by oblivioncth** [comment]
Well color me surprised.

Thanks for the testing!
