### ISSUE TITLE
Seems to interpret XML fractions differently to the game

### ISSUE THREAD

**Issue by lexiccn** [oblivioncth/Stexatlaser#4]
Extracting something like Shipwrecked's minimap atlas causes many of the symbols to end up with parts of a different symbol around the edge - always just 1 pixel wide from the ones I've checked - it seems like it takes an extra pixel, perhaps a rounding error with the fractions?

**Comment by lexiccn** [comment]
Yes - Looking at specific symbols, it removes one line from the bottom and left sides and takes an extra on the right and top

For symbols at the edges of the image, it adds extra lines on the right and top that don't exist in the actual atlas

Not really sure how to work around this either, I considered simply moving the atlas up and right one pixel but again due to it not actually having that space, not possible for this

Edit: The size seems correct though - 64x64 as it should be, it's just off slightly

**Comment by lexiccn** [comment]
Yeah I just realised - this has been patched the version I got from forum Downloads seems updated, got a new one from Releases and they seem okay now!

**Comment by oblivioncth** [comment]
Ah yes,

It seems I forgot to put that last release on the forums page. 

That issue was indeed fixed in the latest release.

Sorry about that.
